{
    "docs": "https://docs.ansible.com/ansible/2.9/dev_guide/testing/sanity/import.html",
    "results": [
        {
            "message": "The test `ansible-test sanity --test import --python 3.7` [[explain](https://docs.ansible.com/ansible/2.9/dev_guide/testing/sanity/import.html)] failed with 1 error:",
            "output": "plugins/modules/transfer.py:61:0: traceback: ModuleNotFoundError: No module named 'boto3'"
        }
    ],
    "verified": false
}
